language: 'node_js'
node_js:
  - 'node'
  - '8'

services:
  - mongodb

# FIXME: Find a better way to cache all node_modules
cache:
  directories:
    - 'node_modules'
    - 'packages/joi-phone/node_modules'
    - 'packages/joi-query/node_modules'
    - 'packages/koa-acl/node_modules'
    - 'packages/koa-boom/node_modules'
    - 'packages/koa-error-handler/node_modules'
    - 'packages/koa-health-check/node_modules'
    - 'packages/koa-joi-validate/node_modules'
    - 'packages/koa-mongoose-model-stream-export/node_modules'
    - 'packages/koa-multipart-form/node_modules'
    - 'packages/koa-nunjucks/node_modules'
    - 'packages/koa-query-fields/node_modules'
    - 'packages/koa-visibility/node_modules'
    - 'packages/mongoose-archive/node_modules'
    - 'packages/redux-api-middleware/node_modules'
    - 'packages/redux-helpers/node_modules'
    - 'packages/redux-router-transitions-middleware/node_modules'
    - 'packages/universal-api-client/node_modules'

install:
  - 'npm install'

script:
  - 'npm run bootstrap'
  - 'npm run build'
  - 'npm run test'

before_deploy:
  - 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $HOME/.npmrc 2> /dev/null'

after_deploy:
  - 'rm $HOME/.npmrc'

deploy:
  provider: 'script'
  script: 'npm run publish'
  skip_cleanup: true
  on:
    node: '8'
    branch: 'release'
